<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>{{pdf_row_separator}}

<?php if ($_specificInfo = $this->getInfo()->getAdditionalInformation()): ?>
    <?php foreach ($_specificInfo as $_label => $_value):
        if ($_label == "statusUrl")
            continue;
        ?>
        <?php
        if ($_label == "transId") {
            $_label = "Transaction Id";
        } else if ($_label == "gid") {
            $_label = "GID";
        } else if ($_label == "status") {
            $_label = "Status";
        }
        ?>
        <?php echo $_label ?>: <?php echo implode($this->getValueAsArray($_value), ' ') ?>{{pdf_row_separator}}
    <?php endforeach; ?>
<?php endif; ?>

<?php echo implode($this->getChildPdfAsArray(), '{{pdf_row_separator}}') ?>
