<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>

<?php if ($_specificInfo = $this->getInfo()->getAdditionalInformation()): ?>
    <table>
        <?php foreach ($_specificInfo as $_label => $_value):
            if ($_label == "statusUrl")
                continue;
            ?>
            <tr>
                <?php
                if ($_label == "transId") {
                    $_label = "Transaction Id";
                } else if ($_label == "gid") {
                    $_label = "GID";
                } else if ($_label == "status") {
                    $_label = "Status";
                }
                ?>
                <td><?php echo $this->escapeHtml($_label) ?>:</td>
                <td><?php echo nl2br(implode($this->getValueAsArray($_value, true), "\n")) ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>

<?php echo $this->getChildHtml() ?>
